language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: QVpP1765xvEU13dnhhXh80RE6qDMsnqMRQ/h1mwBMNlxo6FLSVMV2w85mRtkDrYl3czl/x8wfWhEMsLFYKle+cxDgXKtbjljqXuDukVQPveqXAw9MTImS5o2OTnjnB7UNPARuJXNKfpOA8ikqtoGYQiO3Qp+PbQms852zm2yE78i4FCarSfx2paorCS6lS8OKgnKlKOfrscXdOTfmEh0A1FjO1sRdZBZyZNqch7Vndrugs77D1mjDbyfYR5RBoo/jHXakpIBGWl7DXImoXoEoFRNoWEs239FWmtVTv/wu8RjlIHlpbMqrV3sXOH2WAb8B5lnt3syM5wQaeScvOulGGARYO3wvFCoZyRSAG5sat+clrcGgvD20w4RjrBeqV+Ldi2W3gR0BTGCDgcUGtWajtSaFDiAhpVCsWEvaRFB8W6GJdL62qDiqFDbWGQrfmYBLR/iU9XcAxVWwSFwHkMgyEODHHRBkszJhH5US3dHOJ5t1QERNkD+UbwpCQRlgyL27PbPtog7ZFetN4sTQ4PYgE4jeNuBK8AXsOdFpwc3covEb4ub14YdB1Jep28IKmZ2RLGWEMq+FsL+j4z86RCmGrXi/+zSVSaC5FOhRBguaxxpiPW5ZA8IIeHTK7ZcCVugCOSJ0e5OiLuXH1c8TVEUy4hrBBfBFWdhJvxisbX4+k0=
  app: RandyS-noteful-v3
  on:
    repo: thinkful-ei26/RandyS-noteful-v3
